name: Create Resource Pack Zip
on: [ release ]
jobs:  
  CreateResourcePack:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install zip
        run: apt install -y zip
      - name: Zip Pack
        run: zip -r release.zip ${{ github.workspace }}
      - name: upload zip to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: release.zip
